In [8]:
import numpy as np
from matplotlib import pyplot as plt
import nibabel as nib
import ipywidgets as widgets

In [17]:
file = nib.load('../../../Data/OpenfMRI/ds000115_R2.0.0/sub-03/func/sub-03_task-letter1backtask_bold.nii.gz')
print(file)

<class 'nibabel.nifti1.Nifti1Image'>
data shape (64, 64, 36, 137)
affine: 
[[-3.99977493e+00  6.25283318e-03  4.19654548e-02  1.31784821e+02]
 [ 7.13006221e-03  3.99911761e+00  8.37076157e-02 -1.14343925e+02]
 [ 4.18253504e-02 -8.37777182e-02  3.99890327e+00 -6.58145447e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b'?TR:2500.000 TE:27'
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  4  64  64  36 137   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [-1.0000000e+00  4.0000000e+00  4.0000000e+00  3.9999995e+00
  2.5000000e+00  1.0000000e+00  1.0000000e+00  4.4254809e+04]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end

In [18]:
image = file.get_fdata()
mean = np.mean(image, axis=3)
var = np.var(image, axis=3)

In [19]:
@widgets.interact(idx=(0, mean.shape[2] - 1, 1))
def show_slice(idx=0):
    plt.figure(figsize=(18,6))
    plt.subplot(1,2,1)
    plt.imshow(mean[:,:,idx], vmax=mean.max(), vmin=mean.min())
    plt.colorbar()

    plt.subplot(1,2,2)
    plt.imshow(var[:,:,idx], vmax=var.max(), vmin=var.min())
    plt.colorbar()
    plt.show()

interactive(children=(IntSlider(value=0, description='idx', max=35), Output()), _dom_classes=('widget-interact…